#!/bin/bash

if [[ "$(basename $0)" == "post-merge" ]]; then
  PREVIOUS_HEAD=ORIG_HEAD
else
  PREVIOUS_HEAD=$1
fi

# if style changed (and less available), rebuild sourcemaps
if [[
  ! -z "$(git diff $PREVIOUS_HEAD notebook/static/*/js/**.js)"
]]; then
  echo "rebuilding javascript"
  python setup.py js || echo "fail to rebuild javascript"
fi

if [[
  ! -z "$(git diff $PREVIOUS_HEAD notebook/static/*/less/**.less)"
]]; then
  echo "rebuilding css sourcemaps"
  python setup.py css || echo "fail to recompile css"
fi
