version: 2
sphinx:
  configuration: docs/source/conf.py
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
    nodejs: "16"
python:
  install:
    # install notebook itself
    - method: pip
      path: ".[docs]"
