/*-----------------------------------------------------------------------------
| Copyright (c) Jupyter Development Team.
| Distributed under the terms of the Modified BSD License.
|----------------------------------------------------------------------------*/

/* This file was auto-generated by ensurePackage() in @jupyterlab/buildutils */
import '@jupyter-notebook/application/style/index.js';
import '@jupyter-notebook/ui-components/style/index.js';
import '@jupyter-notebook/application-extension/style/index.js';
import '@jupyter-notebook/console-extension/style/index.js';
import '@jupyter-notebook/docmanager-extension/style/index.js';
import '@jupyter-notebook/documentsearch-extension/style/index.js';
import '@jupyter-notebook/help-extension/style/index.js';
import '@jupyter-notebook/lab-extension/style/index.js';
import '@jupyter-notebook/notebook-extension/style/index.js';
import '@jupyter-notebook/terminal-extension/style/index.js';
import '@jupyter-notebook/tree/style/index.js';
import '@jupyter-notebook/tree-extension/style/index.js';
