/*-----------------------------------------------------------------------------
| Copyright (c) Jupyter Development Team.
| Distributed under the terms of the Modified BSD License.
|----------------------------------------------------------------------------*/

/* This file was auto-generated by ensurePackage() in @jupyterlab/buildutils */
import '@jupyterlab/filebrowser/style/index.js';
import '@jupyterlab/ui-components/style/index.js';
import '@lumino/widgets/style/index.js';
import '@jupyter-notebook/tree/style/index.js';
import '@jupyterlab/application/style/index.js';
import '@jupyterlab/apputils/style/index.js';
import '@jupyterlab/running/style/index.js';
import '@jupyterlab/settingeditor/style/index.js';

import './base.css';
