name: Binder Badge
on:
  pull_request_target:
    types: [opened]

permissions:
  contents: read

jobs:
  binder:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: jupyterlab/maintainer-tools/.github/actions/binder-link@b48fcdb87e70c45789abd80d4042b06641e47b46 # v1
        with:
          github_token: ${{ secrets.github_token }}
          url_path: tree
