name: Binder Badge
on:
  pull_request_target:
    types: [opened]

permissions:
  contents: read

jobs:
  binder:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: jupyterlab/maintainer-tools/.github/actions/binder-link@94b14ddfbdd1ed651e9f9343ae2409ab5c73a6a8 # v1
        with:
          github_token: ${{ secrets.github_token }}
          url_path: tree
