name: Binder Badge
on:
  pull_request_target:
    types: [opened]

permissions:
  contents: read

jobs:
  binder:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: jupyterlab/maintainer-tools/.github/actions/binder-link@21b1cac622018fd37ec13a1c8081da814e10d94e # v1.0.0
        with:
          github_token: ${{ secrets.github_token }}
          url_path: tree
